# インポート

In [1]:
import numpy as np

# 一対比較行列を作る(2×2)

In [28]:
# 空の行列をつくる(2×2)
A = np.zeros((2, 2))

# 行列の上半分を入力する
A[0][1] = 3

# 行列の下半分を入力する
for i in range(2):
    for j in range(2):
        if i > j:
            A[i][j] = 1/A[j][i]

# 対角行列を1にする
np.fill_diagonal(A, 1)
A

array([[1.        , 3.        ],
       [0.33333333, 1.        ]])

# 一対比較行列を作る(3×3)

In [ ]:
# 空の行列をつくる(3×3)
C = np.zeros((3, 3))

# 行列の上半分を入力する
C[0][1] = 3
B[0][2] = 5
B[1][2] = 7

# 行列の下半分を入力する
for i in range(3):
    for j in range(3):
        if i > j:
            B[i][j] = 1/C[j][i]

# 対角行列を1にする
np.fill_diagonal(C, 1)
C

array([[1.        , 3.        , 5.        ],
       [0.33333333, 1.        , 7.        ],
       [0.2       , 0.14285714, 1.        ]])

# 行列から幾何平均法でウェイトを求める

## 行列から幾何平均を求める

In [2]:
# 配列の要素全てをかけ算する
np.prod([1, 2, 3])

6

In [3]:
# 計算用行列
mat = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

np.prod(mat, axis = 1) # axis = 1で行ごとに要素全てをかけ算する

array([  6, 120, 504])

In [4]:
mat.shape

(3, 3)

In [5]:
mat.shape[0] #これで、最初の要素にアクセスする。つまり、行列の行数は3

3

In [6]:
# 計算用行列
mat = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])


product = np.prod(mat, axis = 1)
geo_mean = product ** (1 / mat.shape[0])
geo_mean

array([1.81712059, 4.93242415, 7.95811442])

## 幾何平均からウェイトを求める

In [7]:
# 計算用行列
mat = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])


product = np.prod(mat, axis = 1)
geo_mean = product ** (1 / mat.shape[0])

geo_mean / np.sum(geo_mean) # ウェイト

array([0.12354927, 0.33536432, 0.5410864 ])

## 行列から幾何平均法でウェイトを求める関数

In [8]:
def geometric_mean_weights(matrix):
    product = np.prod(matrix, axis = 1) # 行方向に各要素を乗じた値を求める
    geo_mean = product ** (1 / matrix.shape[0]) # 幾何平均を求める
    return geo_mean / np.sum(geo_mean) # ウェイトを求める

In [9]:
# 計算用行列
mat = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
geometric_mean_weights(mat)

array([0.12354927, 0.33536432, 0.5410864 ])

In [30]:
geometric_mean_weights(A)

array([0.75, 0.25])

In [ ]:
geometric_mean_weights(C)

array([0.6017683 , 0.32363674, 0.07459497])

# 行列の操作練習

In [10]:
mat1 = np.array([[1, 5, 3],
                [1/5, 1, 2],
                [1/3, 1/2, 1]])

mat2 = np.array([[1, 7, 2],
                [1/7, 1, 5],
                [1/2, 1/5, 1]])



In [11]:
geometric_mean_weights(mat1)

array([0.65707139, 0.19630686, 0.14662175])

In [12]:
geometric_mean_weights(mat2)

array([0.63959961, 0.23722266, 0.12317773])

In [13]:
criteria_weights_practice = np.array([0.3, 0.7])

In [14]:
np.array([geometric_mean_weights(mat1), geometric_mean_weights(mat2)]).T

array([[0.65707139, 0.63959961],
       [0.19630686, 0.23722266],
       [0.14662175, 0.12317773]])

In [15]:
np.array([geometric_mean_weights(mat1), geometric_mean_weights(mat2)]).T @ criteria_weights_practice

array([0.64484115, 0.22494792, 0.13021093])

In [16]:
mat = [np.ones((3, 3)) for _ in range(2)]
mat

[array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])]

In [17]:
alt_weights_parctice = [geometric_mean_weights(i) for i in mat]
alt_weights_parctice

[array([0.33333333, 0.33333333, 0.33333333]),
 array([0.33333333, 0.33333333, 0.33333333])]

In [18]:
criteria_weights_practice = np.array([0.3, 0.7])
criteria_weights_practice

array([0.3, 0.7])

In [19]:
alt_weights_parctice_trans =  np.array(alt_weights_parctice).T
alt_weights_parctice_trans

array([[0.33333333, 0.33333333],
       [0.33333333, 0.33333333],
       [0.33333333, 0.33333333]])

In [20]:
alt_weights_parctice_trans @ criteria_weights_practice # @は内積。criteria_weights_practiceはベクトルとして扱われる。

array([0.33333333, 0.33333333, 0.33333333])

# ミニAHPの実装

## 評価基準の一対比較行列の作成

In [61]:
# 空の行列をつくる(2×2)
A = np.zeros((2, 2))

# 行列の上半分を入力する
A[0][1] = 5

# 行列の下半分を入力する
for i in range(2):
    for j in range(2):
        if i > j:
            A[i][j] = 1/A[j][i]

# 対角行列を1にする
np.fill_diagonal(A, 1)
A

array([[1. , 5. ],
       [0.2, 1. ]])

## 評価基準1での一対比較行列

In [62]:
# 空の行列をつくる(3×3)
B = np.zeros((3, 3))

# 行列の上半分を入力する
B[0][1] = 3
B[0][2] = 5
B[1][2] = 7

# 行列の下半分を入力する
for i in range(3):
    for j in range(3):
        if i > j:
            B[i][j] = 1/B[j][i]

# 対角行列を1にする
np.fill_diagonal(B, 1)
B

array([[1.        , 3.        , 5.        ],
       [0.33333333, 1.        , 7.        ],
       [0.2       , 0.14285714, 1.        ]])

## 評価基準2での一対比較行列

In [63]:
# 空の行列をつくる(3×3)
C = np.zeros((3, 3))

# 行列の上半分を入力する
C[0][1] = 3
C[0][2] = 2
C[1][2] = 1

# 行列の下半分を入力する
for i in range(3):
    for j in range(3):
        if i > j:
            C[i][j] = 1/C[j][i]

# 対角行列を1にする
np.fill_diagonal(C, 1)
C

array([[1.        , 3.        , 2.        ],
       [0.33333333, 1.        , 1.        ],
       [0.5       , 1.        , 1.        ]])

## 各行列のウェイトを求める

In [64]:
def geometric_mean_weights(matrix):
    product = np.prod(matrix, axis = 1) # 行方向に各要素を乗じた値を求める
    geo_mean = product ** (1 / matrix.shape[0]) # 幾何平均を求める
    return geo_mean / np.sum(geo_mean) # ウェイトを求める

A_weights = geometric_mean_weights(A) 
B_weights = geometric_mean_weights(B)
C_weights = geometric_mean_weights(C)

In [65]:
# BとCのウェイト配列をくっつける
BC_weights = np.concatenate([[B_weights], [C_weights]], axis=0)


In [66]:
# BCウェイト配列の転置行列に評価行列をかける
BC_weights.T @ A_weights

array([0.59313118, 0.3046712 , 0.10219762])