# インポート

In [1]:
import numpy as np

# 行列から幾何平均法でウェイトを求める

## 行列から幾何平均を求める

In [ ]:
# 配列の要素全てをかけ算する
np.prod([1, 2, 3])

6

In [ ]:
# 計算用行列
mat = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

np.prod(mat, axis = 1) # axis = 1で行ごとに要素全てをかけ算する

array([  6, 120, 504])

In [6]:
mat.shape

(3, 3)

In [ ]:
mat.shape[0] #これで、最初の要素にアクセスする。つまり、行列の行数は3

3

In [8]:
# 計算用行列
mat = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])


product = np.prod(mat, axis = 1)
geo_mean = product ** (1 / mat.shape[0])
geo_mean

array([1.81712059, 4.93242415, 7.95811442])

## 幾何平均からウェイトを求める

In [ ]:
# 計算用行列
mat = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])


product = np.prod(mat, axis = 1)
geo_mean = product ** (1 / mat.shape[0])

geo_mean / np.sum(geo_mean) # ウェイト

array([0.12354927, 0.33536432, 0.5410864 ])

## 行列から幾何平均法でウェイトを求める関数

In [5]:
def geometric_mean_weights(matrix):
    product = np.prod(matrix, axis = 1) # 行方向に各要素を乗じた値を求める
    geo_mean = product ** (1 / matrix.shape[0]) # 幾何平均を求める
    return geo_mean / np.sum(geo_mean) # ウェイトを求める

In [15]:
# 計算用行列
mat = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
geometric_mean_weights(mat)

array([0.12354927, 0.33536432, 0.5410864 ])

# 行列の操作練習

In [13]:
mat1 = np.array([[1, 5, 3],
                [1/5, 1, 2],
                [1/3, 1/2, 1]])

mat2 = np.array([[1, 7, 2],
                [1/7, 1, 5],
                [1/2, 1/5, 1]])



In [14]:
geometric_mean_weights(mat1)

array([0.65707139, 0.19630686, 0.14662175])

In [15]:
geometric_mean_weights(mat2)

array([0.63959961, 0.23722266, 0.12317773])

In [17]:
criteria_weights_practice = np.array([0.3, 0.7])

In [23]:
np.array([geometric_mean_weights(mat1), geometric_mean_weights(mat2)]).T

array([[0.65707139, 0.63959961],
       [0.19630686, 0.23722266],
       [0.14662175, 0.12317773]])

In [24]:
np.array([geometric_mean_weights(mat1), geometric_mean_weights(mat2)]).T @ criteria_weights_practice

array([0.64484115, 0.22494792, 0.13021093])

In [3]:
mat = [np.ones((3, 3)) for _ in range(2)]
mat

[array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])]

In [6]:
alt_weights_parctice = [geometric_mean_weights(i) for i in mat]
alt_weights_parctice

[array([0.33333333, 0.33333333, 0.33333333]),
 array([0.33333333, 0.33333333, 0.33333333])]

In [ ]:
criteria_weights_practice = np.array([0.3, 0.7])
criteria_weights_practice

array([0.3, 0.7])

In [7]:
alt_weights_parctice_trans =  np.array(alt_weights_parctice).T
alt_weights_parctice_trans

array([[0.33333333, 0.33333333],
       [0.33333333, 0.33333333],
       [0.33333333, 0.33333333]])

In [ ]:
alt_weights_parctice_trans @ criteria_weights_practice # @は内積。criteria_weights_practiceはベクトルとして扱われる。

array([0.33333333, 0.33333333, 0.33333333])